# Generated by Django 2.1 on 2020-06-25 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta_dos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50, verbose_name='Etiqueta número dos')),
            ],
            options={
                'verbose_name': 'Etiqueta dos',
            },
        ),
        migrations.CreateModel(
            name='Etiqueta_tres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50, verbose_name='Etiqueta número tres')),
            ],
            options={
                'verbose_name': 'Etiqueta tres',
            },
        ),
        migrations.CreateModel(
            name='Etiqueta_uno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50, verbose_name='Etiqueta número uno')),
            ],
            options={
                'verbose_name': 'Etiqueta uno',
            },
        ),
        migrations.CreateModel(
            name='Etiquetados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Identificados', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Etiquetados',
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=projects.models.identification_project_directory_path)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Identificados',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('contenido', models.TextField(verbose_name='Descripción del proyecto')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('FK_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('FK_tag_dos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Etiqueta_dos', verbose_name='Etiqueta número dos')),
                ('FK_tag_tres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Etiqueta_tres', verbose_name='Etiqueta número tres')),
                ('FK_tag_uno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Etiqueta_uno', verbose_name='Etiqueta número uno')),
            ],
            options={
                'verbose_name': 'Proyecto',
            },
        ),
        migrations.CreateModel(
            name='Repositorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repositorio', models.FileField(upload_to=projects.models.repository_project_directory_path)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('FK_Etiqueta_dos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Etiqueta_dos', verbose_name='FK Tag dos')),
                ('FK_Etiqueta_tres', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Etiqueta_tres', verbose_name='FK Tag tres')),
                ('FK_Etiqueta_uno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Etiqueta_uno', verbose_name='FK Tag uno')),
                ('FK_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Proyecto', verbose_name='FK proyecto')),
            ],
            options={
                'verbose_name': 'Banco de imágenes',
            },
        ),
        migrations.AddField(
            model_name='imagen',
            name='FK_proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Proyecto', verbose_name='FK de proyecto'),
        ),
        migrations.AddField(
            model_name='imagen',
            name='OtO_identificar',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.Etiquetados', verbose_name='Identificados'),
        ),
    ]
