# Generated by Django 2.1 on 2020-06-26 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='OtO_identificar',
        ),
        migrations.AddField(
            model_name='imagen',
            name='FK_identificar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Etiquetados', verbose_name='Identificados'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='FK_tag_dos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Etiqueta_dos', verbose_name='Etiqueta número dos'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='FK_tag_tres',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Etiqueta_tres', verbose_name='Etiqueta número tres'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='FK_tag_uno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Etiqueta_uno', verbose_name='Etiqueta número uno'),
        ),
    ]
