# Generated by Django 2.1 on 2020-07-12 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200625_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50, verbose_name='Etiqueta')),
            ],
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='FK_tag_dos',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='FK_tag_tres',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='FK_tag_uno',
        ),
        migrations.RemoveField(
            model_name='repositorio',
            name='FK_Etiqueta_dos',
        ),
        migrations.RemoveField(
            model_name='repositorio',
            name='FK_Etiqueta_tres',
        ),
        migrations.RemoveField(
            model_name='repositorio',
            name='FK_Etiqueta_uno',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='etiqueta',
            field=models.CharField(default=-1.0, max_length=200, verbose_name='Etiqueta número uno'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Etiqueta_dos',
        ),
        migrations.DeleteModel(
            name='Etiqueta_tres',
        ),
        migrations.DeleteModel(
            name='Etiqueta_uno',
        ),
        migrations.AddField(
            model_name='etiqueta',
            name='FK_proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FKProyect', to='projects.Proyecto', verbose_name='FK proyecto'),
        ),
        migrations.AddField(
            model_name='repositorio',
            name='FK_Etiqueta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Etiqueta', verbose_name='FK Tag'),
        ),
    ]
