# Generated by Django 2.1 on 2020-07-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200711_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repositorio',
            name='FK_Etiqueta',
        ),
        migrations.AddField(
            model_name='repositorio',
            name='Etiqueta',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Etiqueta'),
        ),
    ]
