# Generated by Django 2.1 on 2020-06-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='Carrusel de inicio', verbose_name='Imagenes para el carrusel'),
        ),
    ]
